version: '3.5'

services:
  crdb:
    image: cockroachdb/cockroach:v19.2.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"

  golang:
    build:
      context: .
      target: build-release-stage
    ports:
      - "3000:3000"
    command: sh -c "sleep 20 && /golang-fiber-gorm-crdb-docker"
    depends_on:
      - crdb